### ISSUE TITLE
Handle connection reset by the client?

### ISSUE THREAD

**Issue by DeepDiver1975** [hhxsv5/php-sse#1]
From my understanding we should check for connection_aborted() and exit the loop so that the server can finally terminate the script.

Or am I missing anything?

THX

**Comment by hhxsv5** [comment]
Thanks for your feedback, you are right.

In most cases, this will not be a problem, because [ini.ignore-user-abort](https://secure.php.net/manual/en/misc.configuration.php#ini.ignore-user-abort) is false by default.

But if you set ini.ignore-user-abort to true or call `ignore_user_abort(true);`, it will cause the program does not quit, always loop. This is very bad. So we need to check the connection abort.

**Comment by carlnewton** [comment]
Hi @hhxsv5, when running my application on Symfony server, `ignore_user_abort` is set to false, however I'm not able to exit the loop upon closing the source. Whether doing it manually or closing the window, the loop continues to run.

I have tried adding this to the JavaScript, though from what you've said above, it doesn't sound necessary:
```
$(window).on("unload", function(e) {
    source.close();
});
```

I have also tried adding a `connection_aborted()` check inside the loop:
```
        $response = new StreamedResponse();
        $response->headers->set('Content-Type', 'text/event-stream');
        $response->headers->set('Cache-Control', 'no-cache');
        $response->headers->set('Connection', 'keep-alive');
        $response->headers->set('X-Accel-Buffering', 'no');

        $response->setCallback(function() {
            (new SSE())->start(new Update(function() {

                if(connection_aborted()) {
                    exit;
                }
                ...
```
Is this something you're able to replicate on Symfony server, or have I made a mistake somewhere?

Many thanks.
